apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: joshishrihari/cart-service:latest
          ports:
            - containerPort: 6000
          env:
            - name: PORT
              value: "6000"
            - name: MONGO_URI
              value:
            - name: JWT_SECRET
              value: "XHcS6gl7MTkX4RRHpJRsG7crWTLDUv8HPXbDGcZIXXU="
            - name: ALGORITHM
              value: "HS256"