apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  MYSQL_HOST: host.minikube.internal
  MYSQL_DB: auth
  MYSQL_PORT: "3306"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: products-config
data:
  MYSQL_HOST: host.minikube.internal
  MYSQL_DB: products
  MYSQL_PORT: "3306"
