apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products-container
          image: ninadm13/products-dc:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: products-config
            - secretRef:
                name: global-db-secret
