apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: ninadm13/consumer-dc:latest # Replace with your image
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_QUEUE
              value: "order_queue"
            - name: GMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: gmail-secret
                  key: gmail_user
            - name: GMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: gmail-secret
                  key: gmail_pass
